[web]
title = "OpenAI, Not CloseAI"
subtitle = "真诚、友善、团结、专业"
domain = "new.oaifree.com"
notice_enable = true
notice_title = "**欢迎来到本镜像站**"
notice_subtitle = "本服务基于@Neo的oaifree服务，由@Chenyme制作登录管理界面，如果觉得好用麻烦给个Star叭！  "
notice_style = "outline"
notice_color = "dark"
notice_banner = false
super_user = "admin"
super_key = "12345678"
user_refresh = true
refresh_all = true
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
