[linux_do]
OPENED = false
CLIENT_ID = ""
CLIENT_SECRET = ""
REDIRECT_URI = "http://localhost:8501/"
AUTHORIZATION_ENDPOINT = "https://connect.linux.do/oauth2/authorize"
TOKEN_ENDPOINT = "https://connect.linux.do/oauth2/token"
USER_ENDPOINT = "https://connect.linux.do/api/user"

[linux_do_1]
chatgpt = true
claude = false
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
set1 = ""
set2 = ""
set3 = ""
set4 = ""
set5 = ""

[linux_do_2]
chatgpt = true
claude = false
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
set1 = ""
set2 = ""
set3 = ""
set4 = ""
set5 = ""

[linux_do_3]
chatgpt = true
claude = true
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
set1 = ""
set2 = ""
set3 = ""
set4 = ""
set5 = ""

[linux_do_4]
chatgpt = true
claude = true
site_limit = ""
expires_in = 0
gpt35_limit = -1
gpt4_limit = -1
show_conversations = "false"
set1 = ""
set2 = ""
set3 = ""
set4 = ""
set5 = ""

[setting]
set1 = 1
set2 = 2
set3 = 3
set4 = 4
set5 = 5
set6 = 6
set7 = 7
set8 = 8
set9 = 9
set10 = 10
set11 = 11
set12 = 12
set13 = 13
set14 = 14
set15 = 15
set16 = 16
set17 = 17
set18 = 18
set19 = 19
set20 = 20
set21 = 21
set22 = 22
set23 = 23
set24 = 24
set25 = 25
